name: Deploy React Application

on:
  push:
    branches:
      - deployment

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front-end
    steps:
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD}}
